"""add admin customer accounts and login sessions

Revision ID: 49e4ab87c1cf
Revises: d7e7c722c0b8
Create Date: 2026-10-05 18:05:42.353183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e4ab87c1cf'
down_revision: Union[str, Sequence[str], None] = 'd7e7c722c0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_accounts',
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('failed_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('failed_attempts >= 0', name='ck_admin_failed_attempts'),
    sa.CheckConstraint('length(password_hash) > 0', name='ck_admin_password_hash'),
    sa.CheckConstraint('username = lower(trim(username)) AND length(username) > 0', name='ck_admin_username'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customer_accounts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('failed_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('failed_attempts >= 0', name='ck_customer_account_failed_attempts'),
    sa.CheckConstraint('length(password_hash) > 0', name='ck_customer_account_password_hash'),
    sa.CheckConstraint('username = lower(trim(username)) AND length(username) > 0', name='ck_customer_account_username'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('login_sessions',
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('customer_account_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(admin_id IS NOT NULL) <> (customer_account_id IS NOT NULL)', name='ck_login_session_one_account'),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_account_id'], ['customer_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_login_sessions_admin_id'), 'login_sessions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_login_sessions_customer_account_id'), 'login_sessions', ['customer_account_id'], unique=False)
    op.create_index(op.f('ix_login_sessions_expires_at'), 'login_sessions', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_sessions_expires_at'), table_name='login_sessions')
    op.drop_index(op.f('ix_login_sessions_customer_account_id'), table_name='login_sessions')
    op.drop_index(op.f('ix_login_sessions_admin_id'), table_name='login_sessions')
    op.drop_table('login_sessions')
    op.drop_table('customer_accounts')
    op.drop_table('admin_accounts')
    # ### end Alembic commands ###
