"""Create initial CX schema

Revision ID: d7e7c722c0b8
Revises: 
Create Date: 2026-10-04 15:13:24.021933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7e7c722c0b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_brands_name_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_customers_name_not_blank'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'id', name='uq_customers_brand_id')
    )
    op.create_index(op.f('ix_customers_brand_id'), 'customers', ['brand_id'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('return', 'refund', 'shipping', 'cancellation')", name='ck_knowledge_entries_category'),
    sa.CheckConstraint('length(trim(content)) > 0', name='ck_knowledge_entries_content_not_blank'),
    sa.CheckConstraint('length(trim(title)) > 0', name='ck_knowledge_entries_title_not_blank'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_entries_brand_category', 'knowledge_entries', ['brand_id', 'category'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_brand_id'), 'knowledge_entries', ['brand_id'], unique=False)
    op.create_table('orders',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=80), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='placed', nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('placed', 'shipped', 'delivered', 'cancelled')", name='ck_orders_status'),
    sa.CheckConstraint('length(trim(item_name)) > 0', name='ck_orders_item_not_blank'),
    sa.CheckConstraint('length(trim(order_number)) > 0', name='ck_orders_number_not_blank'),
    sa.ForeignKeyConstraint(['brand_id', 'customer_id'], ['customers.brand_id', 'customers.id'], name='fk_orders_brand_customer', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'customer_id', 'id', name='uq_orders_brand_customer_id'),
    sa.UniqueConstraint('brand_id', 'order_number', name='uq_orders_brand_number')
    )
    op.create_index('ix_orders_brand_customer', 'orders', ['brand_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_orders_brand_id'), 'orders', ['brand_id'], unique=False)
    op.create_table('conversations',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'closed')", name='ck_conversations_status'),
    sa.ForeignKeyConstraint(['brand_id', 'customer_id', 'order_id'], ['orders.brand_id', 'orders.customer_id', 'orders.id'], name='fk_conversations_customer_order', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['brand_id', 'customer_id'], ['customers.brand_id', 'customers.id'], name='fk_conversations_brand_customer', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'id', name='uq_conversations_brand_id')
    )
    op.create_index('ix_conversations_brand_customer', 'conversations', ['brand_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_brand_id'), 'conversations', ['brand_id'], unique=False)
    op.create_index('ix_conversations_customer_order', 'conversations', ['brand_id', 'customer_id', 'order_id'], unique=False)
    op.create_table('messages',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sender_role IN ('customer', 'agent')", name='ck_messages_sender_role'),
    sa.CheckConstraint('length(trim(content)) > 0', name='ck_messages_content_not_blank'),
    sa.ForeignKeyConstraint(['brand_id', 'conversation_id'], ['conversations.brand_id', 'conversations.id'], name='fk_messages_brand_conversation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'conversation_id', 'id', name='uq_messages_brand_conversation_id')
    )
    op.create_index(op.f('ix_messages_brand_id'), 'messages', ['brand_id'], unique=False)
    op.create_index('ix_messages_conversation_created', 'messages', ['brand_id', 'conversation_id', 'created_at'], unique=False)
    op.create_table('reply_generations',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('customer_message_id', sa.UUID(), nullable=False),
    sa.Column('customer_message_snapshot', sa.Text(), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('agent_edited_response', sa.Text(), nullable=True),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('final_message_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='generated', nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status != 'sent' OR (final_message_id IS NOT NULL AND final_response IS NOT NULL)", name='ck_reply_generations_sent_has_message'),
    sa.CheckConstraint("status IN ('generated', 'needs_review', 'sent', 'failed')", name='ck_reply_generations_status'),
    sa.CheckConstraint('length(trim(customer_message_snapshot)) > 0', name='ck_reply_generations_customer_snapshot_not_blank'),
    sa.CheckConstraint('length(trim(model_name)) > 0', name='ck_reply_generations_model_not_blank'),
    sa.ForeignKeyConstraint(['brand_id', 'conversation_id', 'customer_message_id'], ['messages.brand_id', 'messages.conversation_id', 'messages.id'], name='fk_reply_generations_customer_message', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['brand_id', 'conversation_id', 'final_message_id'], ['messages.brand_id', 'messages.conversation_id', 'messages.id'], name='fk_reply_generations_final_message', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['brand_id', 'conversation_id'], ['conversations.brand_id', 'conversations.id'], name='fk_reply_generations_brand_conversation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('final_message_id')
    )
    op.create_index(op.f('ix_reply_generations_brand_id'), 'reply_generations', ['brand_id'], unique=False)
    op.create_index('ix_reply_generations_conversation_created', 'reply_generations', ['brand_id', 'conversation_id', 'created_at'], unique=False)
    op.create_index('ix_reply_generations_customer_message', 'reply_generations', ['brand_id', 'conversation_id', 'customer_message_id'], unique=False)
    op.create_index('ix_reply_generations_final_message', 'reply_generations', ['brand_id', 'conversation_id', 'final_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reply_generations_final_message', table_name='reply_generations')
    op.drop_index('ix_reply_generations_customer_message', table_name='reply_generations')
    op.drop_index('ix_reply_generations_conversation_created', table_name='reply_generations')
    op.drop_index(op.f('ix_reply_generations_brand_id'), table_name='reply_generations')
    op.drop_table('reply_generations')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_index(op.f('ix_messages_brand_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_customer_order', table_name='conversations')
    op.drop_index(op.f('ix_conversations_brand_id'), table_name='conversations')
    op.drop_index('ix_conversations_brand_customer', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_orders_brand_id'), table_name='orders')
    op.drop_index('ix_orders_brand_customer', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_knowledge_entries_brand_id'), table_name='knowledge_entries')
    op.drop_index('ix_knowledge_entries_brand_category', table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index(op.f('ix_customers_brand_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('brands')
    # ### end Alembic commands ###
